import { ParticleBackground } from '@/components/ui/ParticleBackground'
import Link from 'next/link'

export const metadata = { title: 'Privacy Policy — silvar.gg' }

const LAST_UPDATED = 'June 1, 2025'

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-10">
      <h2 className="text-lg font-bold text-[#00f2ff] mb-4 uppercase tracking-wide">{title}</h2>
      <div className="space-y-3 text-[#94a3b8] text-sm leading-relaxed">{children}</div>
    </section>
  )
}

function P({ children }: { children: React.ReactNode }) {
  return <p>{children}</p>
}

function Li({ children }: { children: React.ReactNode }) {
  return <li className="flex gap-2"><span className="text-[#00f2ff] shrink-0">—</span><span>{children}</span></li>
}

export default function PrivacyPage() {
  return (
    <>
      <ParticleBackground />
      <div className="relative z-10 max-w-3xl mx-auto px-6 py-14">
        {/* Header */}
        <div className="mb-10">
          <p className="text-xs text-[#64748b] uppercase tracking-widest mb-2">Legal</p>
          <h1 className="text-4xl font-black text-[#e2e8f0] mb-3">
            Privacy <span className="gradient-cyan">Policy</span>
          </h1>
          <p className="text-sm text-[#64748b]">Last updated: {LAST_UPDATED}</p>
        </div>

        <div className="glass rounded-2xl border border-[rgba(0,242,255,0.1)] p-8">

          <Section title="1. Overview">
            <P>silvar.gg ("we", "us", "the Platform") respects your privacy. This policy explains what personal information we collect, how we use it, and your rights regarding it.</P>
            <P>By using silvar.gg you agree to the collection and use of information in accordance with this policy. We collect only what we need to operate the Platform and we don't sell your data to anyone.</P>
          </Section>

          <Section title="2. Information We Collect">
            <P><strong className="text-[#e2e8f0]">When you log in via Discord OAuth:</strong></P>
            <ul className="space-y-2 mt-2 mb-4">
              <Li>Discord user ID, username, and avatar (provided by Discord)</Li>
              <Li>Email address (provided by Discord, used for account identification only)</Li>
            </ul>
            <P><strong className="text-[#e2e8f0]">Information you choose to provide:</strong></P>
            <ul className="space-y-2 mt-2 mb-4">
              <Li>Roblox username (for trade coordination)</Li>
              <Li>Display name and bio</Li>
              <Li>Profile avatar and banner URLs</Li>
              <Li>Social media profile links (Twitter, YouTube, Discord)</Li>
            </ul>
            <P><strong className="text-[#e2e8f0]">Activity data generated by using the Platform:</strong></P>
            <ul className="space-y-2 mt-2">
              <Li>Sapphire balance and transaction history</Li>
              <Li>Marketplace listings you create</Li>
              <Li>Purchases and Blind Box openings</Li>
              <Li>Inventory items</Li>
              <Li>Support tickets you submit</Li>
            </ul>
          </Section>

          <Section title="3. Information We Do NOT Collect">
            <ul className="space-y-2">
              <Li>Payment card numbers or bank details — all payments are handled directly by Stripe. We never see or store your card information.</Li>
              <Li>Government ID or identity documents.</Li>
              <Li>Precise location data or IP-based tracking beyond what Supabase logs by default.</Li>
            </ul>
          </Section>

          <Section title="4. How We Use Your Information">
            <ul className="space-y-2">
              <Li>To create and manage your account.</Li>
              <Li>To process Sapphire purchases and display your balance.</Li>
              <Li>To facilitate P2P trades between users.</Li>
              <Li>To display your public seller profile to other users (username, display name, listings, reviews).</Li>
              <Li>To respond to support requests.</Li>
              <Li>To detect and prevent fraud, chargebacks, and prohibited behaviour.</Li>
              <Li>To improve the Platform.</Li>
            </ul>
          </Section>

          <Section title="5. What Is Public vs. Private">
            <P><strong className="text-[#e2e8f0]">Publicly visible to all users:</strong></P>
            <ul className="space-y-2 mt-2 mb-4">
              <Li>Your username, display name, avatar, bio, Roblox username, and social links.</Li>
              <Li>Your active marketplace listings and their prices.</Li>
              <Li>Reviews left about you as a seller.</Li>
            </ul>
            <P><strong className="text-[#e2e8f0]">Private (only you and silvar.gg staff can see):</strong></P>
            <ul className="space-y-2 mt-2">
              <Li>Your Sapphire balance and transaction history.</Li>
              <Li>Your email address.</Li>
              <Li>Your Blind Box opening history and inventory.</Li>
              <Li>Support tickets.</Li>
            </ul>
          </Section>

          <Section title="6. Third-Party Services">
            <P>We use the following third-party services to operate the Platform. Each has its own privacy policy:</P>
            <ul className="space-y-2 mt-2">
              <Li>
                <strong className="text-[#e2e8f0]">Supabase</strong> — our database and authentication provider. Stores all account and transaction data on encrypted servers.{' '}
                <a href="https://supabase.com/privacy" target="_blank" rel="noopener noreferrer" className="text-[#00f2ff] hover:underline">supabase.com/privacy</a>
              </Li>
              <Li>
                <strong className="text-[#e2e8f0]">Stripe</strong> — payment processing. Stripe handles all payment card data. We receive only a confirmation of payment and the amount.{' '}
                <a href="https://stripe.com/privacy" target="_blank" rel="noopener noreferrer" className="text-[#00f2ff] hover:underline">stripe.com/privacy</a>
              </Li>
              <Li>
                <strong className="text-[#e2e8f0]">Discord</strong> — used for login via OAuth. We receive only the data Discord provides during sign-in (username, ID, avatar, email).{' '}
                <a href="https://discord.com/privacy" target="_blank" rel="noopener noreferrer" className="text-[#00f2ff] hover:underline">discord.com/privacy</a>
              </Li>
            </ul>
            <P>We do not share your personal information with any other third parties, advertisers, or data brokers.</P>
          </Section>

          <Section title="7. Cookies & Local Storage">
            <P>We use browser local storage to:</P>
            <ul className="space-y-2 mt-2">
              <Li>Store your shopping cart contents between sessions.</Li>
              <Li>Maintain your login session (via Supabase auth cookies).</Li>
            </ul>
            <P>We do not use advertising cookies or tracking pixels. We do not use Google Analytics or any third-party analytics service.</P>
          </Section>

          <Section title="8. Data Retention">
            <P>We retain your account data for as long as your account is active. If you request account deletion, we will delete your personal information within 30 days, except where we are required to retain it to resolve outstanding disputes, detect fraud, or comply with legal obligations.</P>
            <P>Transaction records (purchases, Sapphire top-ups) may be retained for up to 7 years for financial record-keeping purposes.</P>
          </Section>

          <Section title="9. Your Rights">
            <P>You have the right to:</P>
            <ul className="space-y-2 mt-2">
              <Li><strong className="text-[#e2e8f0]">Access</strong> — request a copy of the personal data we hold about you.</Li>
              <Li><strong className="text-[#e2e8f0]">Correction</strong> — update inaccurate information via your Profile Settings at any time.</Li>
              <Li><strong className="text-[#e2e8f0]">Deletion</strong> — request that we delete your account and associated personal data.</Li>
              <Li><strong className="text-[#e2e8f0]">Portability</strong> — request your data in a machine-readable format.</Li>
            </ul>
            <P>To exercise any of these rights, email <a href="mailto:support@silvar.gg" className="text-[#00f2ff] hover:underline">support@silvar.gg</a>. We will respond within 30 days.</P>
          </Section>

          <Section title="10. Children's Privacy">
            <P>silvar.gg is not directed at children under 13. We do not knowingly collect personal information from children under 13. If you believe a child under 13 has provided us with personal information, contact us immediately and we will delete it.</P>
          </Section>

          <Section title="11. Security">
            <P>We take reasonable technical measures to protect your data, including encrypted database storage via Supabase and HTTPS for all connections. However, no method of transmission over the internet is 100% secure and we cannot guarantee absolute security.</P>
            <P>You are responsible for keeping your Discord account secure, as it is your access method to silvar.gg.</P>
          </Section>

          <Section title="12. Changes to This Policy">
            <P>We may update this Privacy Policy from time to time. We will post the updated date at the top of this page. Significant changes will be announced via site notice. Continued use of the Platform after changes constitutes acceptance.</P>
          </Section>

          <Section title="13. Contact">
            <P>Questions about this Privacy Policy? Email us at <a href="mailto:support@silvar.gg" className="text-[#00f2ff] hover:underline">support@silvar.gg</a>.</P>
          </Section>

        </div>

        <div className="mt-8 text-center">
          <Link href="/terms" className="text-sm text-[#64748b] hover:text-[#00f2ff] transition-colors">
            View our Terms of Service →
          </Link>
        </div>
      </div>
    </>
  )
}
